apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: efs-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: efs-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: efs-app
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"

