apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

nameSuffix: "-task-a"
commonLabels:
  task-group: task-a

replicas:
- name: efs-app
  count: 2

patchesStrategicMerge:
  - pv-pvc.yaml