apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

nameSuffix: "-task-b"
commonLabels:
  task-group: task-b

replicas:
- name: efs-app
  count: 3

patchesStrategicMerge:
  - pv-pvc.yaml