---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 20Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <efs-filesystem-id-for-task-b>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  resources:
    requests:
      storage: 20Gi